# Generated by Django 5.2.5 on 2025-08-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='products.attributevalue'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
